server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:server.p12
    key-store-password: senhaComplexa26041970
    key-store-type: PKCS12
    key-alias: server

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://srv1197.hstgr.io:3306/u417179784_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: u417179784_user
    password: 1uQ=X0gu
    hikari:
      max-lifetime: 18000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
