# application-prod.yml
server:
  port: 8080
  
  ssl:
    enabled: true
    key-store: ${SSL_KEY_STORE}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${SSL_KEY_ALIAS:server}

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
    hikari:
      max-lifetime: ${HIKARI_MAX_LIFETIME}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}