# application-prod.yaml
# Author: oEnzoRibas
server:
  port: 8080
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEY_STORE:}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:}
    key-store-type: PKCS12
    key-alias: ${SSL_KEY_ALIAS:server}
    
spring:
  jpa:
    show-sql: false

