spring:
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: "server"
          keystore:
            location: "classpath:server.p12"
            password: "secret"
            type: "PKCS12"
      pem:
        client:
          truststore:
            certificate: "classpath:client.crt"
  datasource:
    driver-class-name: "org.mariadb.jdbc.Driver"
    url: "jdbc:mariadb://srv1197.hstgr.io:3306/u417179784_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    username: "u417179784_user"
    password: "1uQ=X0gu"
    hikari:
      max-lifetime: 18000
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
    open-in-view: false