 spring.datasource.url=jdbc:h2:mem:yolanda-dbc
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.password=
spring.datasource.username=sa
jwt.secret=n9o4oZ0tE6gfpV09FmdgfbU9Jwsccew2osMzdPLrMHEYq9llYd+tefrzZ3dn/mOhUXqPkzITvFfnbhwV7S/kDg==

#spring.datasource.url=jdbc:mysql://srv1197.hstgr.io:3306/u417179784_database_p?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=u417179784_YdsSC
#spring.datasource.password=~eRYwXZ8Q@
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true


