springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# application-dev.yaml
# Author: oEnzoRibas
server:
  port: 8080
spring:
  flyway:
    enabled: false
    baseline-on-migrate: false
  jpa:
    show-sql: false
